<?xml version="1.0"?>
<package format="2">
  <name>rear_mic_recorder</name>
  <version>0.1.0</version>
  <description>Rear microphone audio recorder package</description>

  <maintainer email="user@example.com">User</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>rospy</exec_depend>
</package>
